version: '3'
# runs the entire rudder pipeline with all supporting services (including rudder) in docker
# set .env such that all services in docker are talking to each other only
services:
  eth-node:
    image: "us-docker.pkg.dev/covalent-project/network/operational-staking:latest-rudder"
    container_name: hardhat-node
    restart: on-failure
    expose:
      - "8545:8545"
    entrypoint: |
      /bin/bash -l -c "
      echo "forked-node-address:" $ERIGON_NODE;
      ./entrypoint.sh;"
    networks:
      - cqt-net
    environment:
      - ERIGON_NODE=${ERIGON_NODE}
    ports:
      - "8545:8545"

  operational-staking:
    image: "us-docker.pkg.dev/covalent-project/network/operational-staking:latest-rudder"
    container_name: proof-chain
    restart: on-failure
    entrypoint: |
      /bin/bash -l -c "
      echo Waiting for hardhat-node to start up...;
      sleep 20;
      echo hard-hat node started!;
      echo "web3-jwt:" $WEB3_JWT;
      npm run docker:deploy;
      nc -v rudder 8008;
      sleep 1000000;"
    depends_on:
      - eth-node
    networks:
      - cqt-net
    ports:
      - "8008:8008"

  ipfs-pinner:
    image: "us-docker.pkg.dev/covalent-project/network/ipfs-pinner:latest"
    volumes:
      - ~/.ipfs:/root/.ipfs/
    container_name: ipfs-pinner
    restart: on-failure
    expose:
      - "4001:4001"
      - "3000:3000"
    environment:
      - WEB3_JWT=${WEB3_JWT}
    networks:
      - cqt-net
    ports:
      - "4001:4001"
      - "3000:3000"

  evm-server:
    image: "us-docker.pkg.dev/covalent-project/network/evm-server:latest"
    container_name: evm-server
    restart: on-failure
    expose:
      - "3002:3002"
    networks:
      - cqt-net
    ports:
      - "3002:3002"

  rudder:
    image: "us-docker.pkg.dev/covalent-project/network/rudder:latest"
    container_name: rudder
    links:
      - "ipfs-pinner:ipfs-pinner"
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      ipfs-pinner:
        condition: service_started
      evm-server:
        condition: service_started
    entrypoint: >
      /bin/bash -l -c "
        echo "ipfs-node-address:" $IPFS_PINNER_URL;
        echo "hardhat-node-address:" $NODE_ETHEREUM_MAINNET;
        echo "brp-op-pk:" $BLOCK_RESULT_OPERATOR_PRIVATE_KEY;
        echo "evm-server-address:" $EVM_SERVER_URL;
        echo Waiting for proof-chain to be deployed...;
        while ! nc -v -l -k -p 8008;
        do
        sleep 1;
        done;
        echo Proof-chain contracts deployed!;
        echo Uploading test files to local .ipfs...;
        curl -F "filedata=@/app/test-data/codec-0.35/encoded/1-17090940-replica-0x7b8e1d463a0fbc6fce05b31c5c30e605aa13efaca14a1f3ba991d33ea979b12b" http://ipfs-pinner:3000/upload;
        curl -F "filedata=@/app/test-data/codec-0.35/encoded/1-17090960-replica-0xc95d44182ee006e79f1352ef32664210f383baa016988d5ab2fd950b52bf22ff" http://ipfs-pinner:3000/upload;
        echo Test bsp files uploaded!;
        cd /app;
        MIX_ENV=docker mix test --trace --slowest 10;
        exit 0;"
    environment:
      - NODE_ETHEREUM_MAINNET=${NODE_ETHEREUM_MAINNET}
      - BLOCK_RESULT_OPERATOR_PRIVATE_KEY=${BLOCK_RESULT_OPERATOR_PRIVATE_KEY}
      - EVM_SERVER_URL=${EVM_SERVER_URL}
      - IPFS_PINNER_URL=${IPFS_PINNER_URL}
    networks:
      - cqt-net

networks:
  cqt-net:
